export enum Roles {
  ANONYMOUS_USER = "ANONYMOUS_USER",
  SUPER_ADMIN_USER = "SUPER_ADMIN_USER",
  WORKER_USER = "WORKER_USER",
  TASKS_SUPPLIER_USER = "TASKS_SUPPLIER_USER",
  BOTH_USER = "BOTH_USER"
}
